#!/bin/bash

_pwd=$(dirname $0)
source ${_pwd}/funcs

export DOTFILES=${HOME}/dotfiles

# Support XDG Base Directory
export XDG_CONFIG_HOME=${HOME}/.config

# OS判定
export PLATFORM=`_platform`

# for macOS
if [[ "${PLATFORM}" == "darwin" ]]; then
  if [[ -e /usr/local/opt/gnu-sed/libexec/gnubin ]]; then
    PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
  fi
  if [[ -e /usr/local/opt/make/libexec/gnubin ]]; then
    PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
  fi
  if [[ -e /usr/local/opt/curl/bin ]]; then
    export PATH="/usr/local/opt/curl/bin:$PATH"
  fi
fi

# Homebrew
[[ -d /usr/local/bin ]] && [[ $PATH =~ /usr/local/bin ]] || export PATH=/usr/local/bin:$PATH
[[ -d /usr/local/sbin ]] && [[ $PATH =~ /usr/local/sbin ]] || export PATH=/usr/local/sbin:$PATH

# ページャ
export PAGER=less

# エディタ設定
export EDITOR=vim

# 区切り文字の設定
export WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'

# ヒストリ設定
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=1000000
export SAVEHIST=1000000

# golang
export GOPATH=$HOME/workspace
export PATH=$GOPATH/bin:$PATH
export GO15VENDOREXPERIMENT=1

# user local bin path
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/local/bin:$PATH

# ghq
export GHQ_ROOT=$GOPATH/src

# rust/cargo
export PATH=${HOME}/.cargo/bin:${PATH}

# pipenv
export PIPENV_SHELL_FANCY=1

# composer
export PATH="${HOME}/.config/composer/vendor/bin:${PATH}"

# nvm
export NVM_DIR="$HOME/.nvm"
export NVM_COMPLETION=true
export NVM_LAZY_LOAD=true

# neovm
export NODE_VERSIONS="$NVM_DIR/versions/node"
export NODE_VERSION_PREFIX=""

# krew
export PATH="${PATH}:${HOME}/.krew/bin"

# clangd
export PATH="/usr/local/opt/llvm/bin:$PATH"

# fzf
export FZF_DEFAULT_COMMAND='fd --hidden --exclude=".git"'

# python
export PATH="/usr/local/opt/python/libexec/bin:$PATH"

# google cloud sdk
export PATH=$HOME/local/google-cloud-sdk/bin:$PATH
source $HOME/local/google-cloud-sdk/completion.zsh.inc

# local bin
export PATH=$HOME/bin:$PATH

# ruby gem
RUBY_GEM_PATH=$HOME/.gem/ruby
if test -d "$RUBY_GEM_PATH"; then
  ls "$RUBY_GEM_PATH" | (while read v
    do
      export PATH="$RUBY_GEM_PATH/$v/bin:$PATH"
    done
  )
fi
