[[plugins]]
# the fastest completion
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_delay = 0
let g:deoplete#enable_ignore_case = 1
let g:deoplete#enable_smart_case = 1
let g:deoplete#enable_refresh_always = 1
let g:deoplete#sources = {}
let g:deoplete#sources._ = ['buffer', 'member', 'omni']
let g:deoplete#sources.go = ['vim-go']
let g:deoplete#file#enable_buffer_path = 1
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
'''

[[plugins]]
# The vim source for deoplete
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
# python source for deoplete
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_source = '''
let g:python_host_prog = system("type python2")
let g:python3_host_prog = system("type python3")
'''

[[plugins]]
# clang source for deoplete
repo = 'tweekmonster/deoplete-clang2'
on_ft = ['c', 'cpp']

[[plugins]]
# Include completion framework for deoplete
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']

[[plugins]]
# javascript completion
repo = 'ternjs/tern_for_vim'
on_ft = 'javascript'
hook_source = '''
let g:tern#command = ["tern"]
let g:tern#arguments = ["--persistent"]
'''

[[plugins]]
# javascript source for deoplete
repo = 'carlitux/deoplete-ternjs'
on_ft = 'javascript'
hook_source = '''
let g:tern_request_timeout = 1
let g:tern_show_signature_in_pum = '0'  " This do disable full signature type on autocomplete
'''

[[plugins]]
# ruby source for deoplete
repo = 'fishbullet/deoplete-ruby'
on_ft = 'ruby'

[[plugins]]
# php source for deoplete
repo = 'lvht/phpcd.vim'
on_ft = 'php'
hook_post_update = '''
composer install
'''
hook_source = '''
let g:deoplete#ignore_sources = get(g:, 'deoplete#ignore_sources', {})
let g:deoplete#ignore_sources.php = ['omni']
'''

[[plugins]]
# terminal
repo = 'kassio/neoterm'
hook_add = '''
let g:neoterm_autoinsert = 1
let g:neoterm_autoscroll = 1
'''

[[plugins]]
repo = 'jsfaint/gen_tags.vim'

[[plugins]]
repo = 'zebult/auto-gtags.vim'
hook_add = '''
let g:auto_update_gtags = 1
'''
