[[plugins]]
# 高速補完
repo = 'Shougo/neocomplete.vim'
on_i = 1
hook_source = '''
let g:neocomplete#enable_at_startup = 1
'''

[[plugins]]
# ruby code completion
repo = "osyo-manga/vim-monster"
depends = "neocomplete"
hook_source = '''
let g:monster#completion#rcodetools#backend = "async_rct_complete"
let g:neocomplete#sources#omni#input_patterns = {
\   "ruby" : '[^. *\t]\.\w*\|\h\w*::',
\}
'''
