format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$kubernetes\
$line_break\
$time\
$username\
$hostname\
$shlvl\
$status\
$character
"""

[git_branch]
style = "green"

[directory]
truncation_length = 100
truncate_to_repo = false
style = "blue"

[time]
disabled = false
format = "$time "
time_format = "%F %TJST"
utc_time_offset = "+9"

[kubernetes]
disabled = false
style = "blue"
format = "[$symbol$context( \\($namespace\\) )]($style)"
