---
version: 2
log-file: /tmp/efm.log
log-level: 1
root-markers:
  - .git/
  - .zshrc

tools:
  go-goimports: &go-goimports
    format-command: "goimports"
    format-stdin: true

languages:
  go:
    - <<: *go-goimports
