#!/bin/bash

set -e

is_setup() {
  echo -n "Do you setup '$1'? [y/N]: "
  while read -r answer; do
    case $answer in
      'y') return 0 ;;
      'N') return 1 ;;
      *) echo -n "Try again because you input incorrect letter. Do you setup '$1'? [y/N]: " ;;
    esac
  done
}

if is_setup 'Xcode Command Line Tools'; then
  xcode-select --install
fi

if is_setup 'Homebrew'; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew doctor
fi

if [ ! -d "$HOME/dotfiles" ]; then
  git clone https://github.com/unblee/dotfiles.git ~/dotfiles
fi

$HOME/dotfiles/scripts/deploy
